[package]
name = "smart-contract-verifier-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smart-contract-verifier = {path = "../smart-contract-verifier"}